#!/usr/bin/env bash
# This script is displaying information about the holbertonschool file.
# use if and, else: check if the file exists and print:
# If the file exists, does not exist, is empty or not, is a regular or not.
file="./school"

if [ -e "$file" ]
then
        echo "school file exists"

                if [ -s "$file" ]
                then
                        echo "school file is not empty"
                else
                        echo "school file is empty"
                fi
                if [ -f "$file" ]
                then
                        echo "school is a regular file"
                fi
else
        echo "school file does not exist"
fi
